-- Migration 050: Ecom-DZ credentials — separated from JSON-in-column approach.
-- The code (vendors.ts, dispatch.ts) now uses `ecom_api_key` / `ecom_api_token`
-- as separate columns instead of storing JSON in the legacy `ecom_token` column.
-- 
-- The actual columns are added in migration_052.
